### ISSUE TITLE
Enable global configuration of registry-url parameter

### ISSUE THREAD

**Issue by thallesdaniell** [CircleCI-Public/gcp-gcr-orb#101]
## Context and Description:

During our migration to utilizing CircleCI orbs, specifically the gcp-gcr orb, we observed that certain parameters, such as registry-url, consistently held the same value across all jobs within a pipeline. Currently, the orb requires specifying the registry-url parameter individually in each job or command, leading to repetitive configurations and increased potential for errors.

To enhance efficiency and maintainability, we propose introducing the capability to define the registry-url parameter globally within the gcp-gcr orb. This adjustment would allow users to set the parameter once at a higher level, ensuring uniformity across all jobs and commands, and reducing redundancy in pipeline configurations.

## Benefits:

 - Consistency: A global setting ensures that all jobs reference the same registry-url, minimizing discrepancies.

 - Simplified Configuration: Reduces the need to repeatedly specify the same parameter, streamlining the setup process.

 - Reduced Error Potential: With a single source of truth for the registry-url, the likelihood of misconfigurations decreases.

## Proposed Implementation:

Introduce a top-level configuration option within the gcp-gcr orb to allow users to define the registry-url globally. This setting would automatically apply to all relevant commands and jobs within the orb, unless explicitly overridden at a lower level.

**Comment by david-montano-circleci** [comment]
Hello @thallesdaniell , thank you for opening the issue and for your comments.
Orbs usually have both jobs and commands. Let's check both scenarios.

With jobs, users can create their own on the fly commands but also reuse existing commands from the same or other orbs.
The current two available jobs for this orb have a `registry-url` parameter which has a default value of `gcr.io` and this parameter is passed down to the commands that are used in the jobs.

Commands are more granular and usually depend on a script to run some logic. Users can identify parts that can be passed down as parameters and this allows jobs to invoke the commands with parameters that where initialized only once at the job level.

This is exactly what is happening with the `registry-url` already and this is why you find it as a parameter in all jobs and commands in this orb. Given all this, I think the orb is already behaving as you are proposing it to work. Maybe I am missing something? Please feel free to clarify.

**Comment by thallesdaniell** [comment]
Currently, while we can define these values as environment variables at the job level, they still need to be referenced explicitly in each command within the job. By enabling a truly global configuration for these parameters within the orb itself, users would no longer need to manually specify them in every job or step, ensuring consistency and simplifying pipeline configurations.

```yaml
version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@x.y.z

jobs:
  build-and-push-slack-bot:
    parameters:
      tag-image:
        description: "Tag for GCR"
        default: "latest"
        type: string

    executor: gcp-gcr/default
    environment:
      GOOGLE_COMPUTE_ZONE: us-central1-a
      GOOGLE_REGISTRY_URL: us-central1-docker.pkg.dev
      GOOGLE_REPOSITORY: docker
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          # The GOOGLE_REGISTRY_URL environment variable will be used here
      - gcp-gcr/build-image:
          image: app-demo
          dockerfile: ./tools/demo/Dockerfile
          tag: ${CIRCLE_SHA1::7}
          # The GOOGLE_REGISTRY_URL and GOOGLE_REPOSITORY environment variables will be used here
      - gcp-gcr/push-image:
          image: app-demo
          tag: ${CIRCLE_SHA1::7}
          # The GOOGLE_REGISTRY_URL and GOOGLE_REPOSITORY environment variables will be used here
      - gcp-gcr/tag-image:
          image: app-demo
          source-tag: ${CIRCLE_SHA1::7}
          target-tag: << parameters.tag-image >>
          # The GOOGLE_REGISTRY_URL and GOOGLE_REPOSITORY environment variables will be used here
```
