### ISSUE TITLE
Pushing to Artifact Registry w/ OIDC doesn't work

### ISSUE THREAD

**Issue by csirmazbendeguz** [CircleCI-Public/gcp-gcr-orb#103]
## Orb version:

0.16.10

## What happened:

I've been trying to get this working for days now.
I'm trying to build and push my image to Artifact Registry using Workload Identity Federation.
Here's my config:

```yaml
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.10
jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          registry-url: europe-west3-docker.pkg.dev
          use_oidc: true
      - gcp-gcr/build-image:
          image: foo
          registry-url: europe-west3-docker.pkg.dev
          repository: docker
      - gcp-gcr/push-image:
          image: foo
          registry-url: europe-west3-docker.pkg.dev
          repository: docker
workflows:
  deploy:
    jobs:
      - build-and-push:
          context:
            - artifact-registry-credentials
```

I have the context `artifact-registry-credentials` with the following environment variables:
- GOOGLE_PROJECT_ID
- GOOGLE_PROJECT_NUMBER
- OIDC_SERVICE_ACCOUNT_EMAIL
- OIDC_WIP_ID
- OIDC_WIP_PROVIDER_ID

I have the Workload Identity Pool and Provider configured in GCP:

```tf
resource "google_iam_workload_identity_pool" "circleci_workload_identity_pool" {
  project = var.google_project_number
  workload_identity_pool_id = "circleci"
  display_name = "CircleCI"
}

resource "google_iam_workload_identity_pool_provider" "circleci_workload_identity_pool_provider" {
  project = var.google_project_number
  workload_identity_pool_id = google_iam_workload_identity_pool.circleci_workload_identity_pool.workload_identity_pool_id
  workload_identity_pool_provider_id = "circleci"
  display_name = "CircleCI"
  attribute_mapping = {
    "google.subject": "assertion.sub"
    "attribute.org_id": "assertion.aud"
  }
  oidc {
    allowed_audiences = [var.circleci_org_id]
    issuer_uri = "https://oidc.circleci.com/org/${var.circleci_org_id}"
  }
}
```

I have a service account for the impersonation:

```tf
resource "google_service_account" "circleci_sa" {
  account_id = "circleci"
  display_name = "CircleCI"
  description = "A service account for CircleCI"
}

resource "google_project_iam_binding" "artifact_registry_reader_iam_binding" {
  project = var.google_project_id
  role = "roles/artifactregistry.reader"
  members = [
    "serviceAccount:${google_service_account.circleci_sa.email}",
  ]
}

resource "google_project_iam_binding" "artifact_registry_writer_iam_binding" {
  project = var.google_project_id
  role = "roles/artifactregistry.writer"
  members = [
    "serviceAccount:${google_service_account.circleci_sa.email}",
  ]
}

resource "google_service_account_iam_binding" "circleci_sa_workload_identity_user" {
  service_account_id = google_service_account.circleci_sa.id
  role = "roles/iam.workloadIdentityUser"
  members = [
    "principalSet://iam.googleapis.com/projects/${var.google_project_number}/locations/global/workloadIdentityPools/${google_iam_workload_identity_pool.circleci_workload_identity_pool.workload_identity_pool_id}/attribute.org_id/${var.circleci_org_id}",
  ]
}

resource "google_service_account_iam_binding" "circleci_sa_service_account_token_creator" {
  service_account_id = google_service_account.circleci_sa.id
  role = "roles/iam.serviceAccountTokenCreator"
  members = [
    "principalSet://iam.googleapis.com/projects/${var.google_project_number}/locations/global/workloadIdentityPools/${google_iam_workload_identity_pool.circleci_workload_identity_pool.workload_identity_pool_id}/attribute.org_id/${var.circleci_org_id}",
  ]
}
```

In the *Initialize gcloud CLI to connect to Google Cloud* step, I see a warning:

```
WARNING: [******************************************************] does not have permission to access projects instance [*****************] (or it may not exist): The caller does not have permission. This command is authenticated as ****************************************************** which is the active account specified by the [core/account] property
```

In the *Push image to GCR* step, I see an error:

```
denied: Permission "artifactregistry.repositories.uploadArtifacts" denied on resource "projects/*****************/locations/europe-west3/repositories/docker" (or it may not exist)
```

## Expected behavior:

I expect CircleCI to build and push an image to my private Artifact Registry.
