### ISSUE TITLE
build-and-push-image started failing with "unknown flag: --file"

### ISSUE THREAD

**Issue by Liiva** [CircleCI-Public/gcp-gcr-orb#104]
## Orb version:

Initially used `circleci/gcp-gcr@0.16.4`, tried upgrading to most recent (`circleci/gcp-gcr@0.16.10`) but this issue is still occurring there.

## What happened:

The build step is failing with an error: `unknown flag: --file`.

Full output on circle ci:
```
+ docker buildx build --file=././.docker/nginx/Dockerfile --tag=***REDACTED*** .
unknown flag: --file

Usage:  docker [OPTIONS] COMMAND [ARG...]

Run 'docker --help' for more information

Exited with code exit status 125
```

Note that this build was passing just fine about a month ago (15-5-2025), but since 3-6-2025 it has been failing consistently. Now I noticed there was a new docker version released on 30-5-2025 (version 28.2.2) which _might_ be related, but could also just be coincidence.

## Expected behavior:

The image should build.

## Additional Information:

My circleci configuration for the build-and-push-image job:

```
      - gcp-gcr/build-and-push-image:
          name: build-nginx-prod-image
          context: **REDACTED**-deployment
          registry-url: europe-west4-docker.pkg.dev
          image: **REDACTED**-nginx
          tag: $CIRCLE_SHA1
          executor: gcp-cli/google
          setup-remote-docker: true
          remote-docker-version: default
          attach-workspace: true
          dockerfile: ./.docker/nginx/Dockerfile
          requires:
            - build-production-application
```
The docker version used inside the circle ci box: `Docker version 28.2.2, build e6534b4`

When I ssh into the box I can reproduce the issue consistently, I tried running a barebone `build` command with no luck:
```
root@3b8cd4dfaf78:~# cd project/
root@3b8cd4dfaf78:~/project# docker buildx build --file=./.docker/nginx/Dockerfile .
unknown flag: --file

Usage:  docker [OPTIONS] COMMAND [ARG...]

Run 'docker --help' for more information
```

I also tried running with `remote-docker-version: docker27` but no luck unfortunately.
