### ISSUE TITLE
path parameters description of build-and-push-image command needs more information

### ISSUE THREAD

**Issue by girards** [CircleCI-Public/gcp-gcr-orb#27]
### Orb version

0.6.1

### What happened

When trying to follow the documentation for the command build-and-push-image, I'm not able to understand how is the path supposed to be configured. I have 2 images that I'm trying to build and push from 2 Dockerfiles : 

![simplified view of architecture](https://user-images.githubusercontent.com/6340743/64323219-58b04f00-cfc4-11e9-92dc-c5f594ffbb67.png)

and my config looking like this : 

``` YAML
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
workflows:
  version: 2
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/frontend
          tag: $CIRCLE_BRANCH
          path: ~/frontend/
      - gcp-gcr/build-and-push-image:
          image: eu.gcr.io/${PROJECT_ID}/backend
          tag: $CIRCLE_BRANCH
          path: ~/project/backend/
```

I tried setting the path to multiple values like `./backend`, `../backend`, same issue with frontend path

### Expected behavior

Could the documentation be more specific to which kind of path is expected ?

**Comment by girards** [comment]
I managed to make it work by doing the following : 

```yaml
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
workflows:
  version: 2
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          dockerfile: frontend/Dockerfile
          image: eu.gcr.io/${PROJECT_ID}/frontend
          tag: $CIRCLE_BRANCH
          path: ~/project/frontend/
      - gcp-gcr/build-and-push-image:
          dockerfile: backend/Dockerfile
          image: eu.gcr.io/${PROJECT_ID}/backend
          tag: $CIRCLE_BRANCH
          path: ~/project/backend/
```

Shouldn't the job handle the fact that with a path, the docker file should be equal to `<<parameters.path>>/$<<parameters.dockerfile>>` with `dockerfile` being defaulted to `Dockerfile`?
