### ISSUE TITLE
gcloud installation failure

### ISSUE THREAD

**Issue by t12g** [CircleCI-Public/gcp-gcr-orb#28]
### Orb version
2.1
### What happened
I encountered a gcloud installation failure:

```
Err:9 http://packages.cloud.google.com/apt cloud-sdk-/main amd64 Packages
  404  Not Found

Reading package lists... Done

W: The repository 'http://packages.cloud.google.com/apt cloud-sdk- Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk-/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Exited with code 100
```

My config:
```
version: 2.1                                                                                                             
orbs:                                                                                                                                                                                                        
  gcp-gcr: circleci/gcp-gcr@0.6.1                                                                                        
jobs:                                                                                                                    
  mvn-push:                                                                                                              
    docker:                                                                                                              
      - image: circleci/openjdk:11.0.2                                                                                   
    steps:                                                                                                               
      - gcp-gcr/gcr-auth                                                                                                 
workflows:                                                                                                               
  build-and-push:                                                                                                        
    jobs:                                                                                                                
      - mvn-push:                                                                                                        
          context: my-context
```

As a reference, circleci/gcp-cli@1.8.2 is working fine. 
### Expected behavior

gcloud should install successfully.
