### ISSUE TITLE
extra_build_args case inconsistencies

### ISSUE THREAD

**Issue by danodonovan** [CircleCI-Public/gcp-gcr-orb#34]
### Orb version `0.7.1`

The "extra build args" parameter name `extra_build_args` is snake case, while all other parameters are kebab case (in this orb and others). In particular cf. 

```
aws-ecr/build-image:
  extra-build-args: <blah>

gcp-gcr/build-image:
  extra_build_args: <bleurgh>
```

If a PR would help please ping me.
