### ISSUE TITLE
How do I tag the branch name slug in gcp-gcr/tag-image?

### ISSUE THREAD

**Issue by giiita** [CircleCI-Public/gcp-gcr-orb#35]
### Orb version

0.7.1

### What happened

In operations such as gitflow, branch names such as `fetature/xxx` are given, but you can't set tags with slush in docker's tags, and gitlab-ci and others provide slug names as environment variables.

Perhaps the scripting feature of GCP-GCR can be used to convert and tag the BRANCH name. But it's not ideal.

Being able to set a script to target-tag is a necessary feature in my opinion.
I'm not familiar with cricleci, so I'm not immediately sure it's possible.

```yaml
      - gcp-gcr/add-image-tag:
          name: tagging_branch_name
          requires:
          image: builtImage
          registry-url: gcr.io
          source-tag: latest
          target-tag: echo $CIRCLE_BRANCH | sed -e "s/[^a-zA-Z]/\-/g"
```

```
ERROR: (gcloud.container.images.add-tag) Invalid tag: echo test/branch/name | sed -e s/[^a-zA-Z]/-/g
```
