### ISSUE TITLE
Support artifact registry Docker repository.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [CircleCI-Public/gcp-gcr-orb#47]
## Describe Request:

GCP recently released Artifact Registry that supports docker registry as well

https://cloud.google.com/artifact-registry/docs/docker/authentication#gcloud-helper

This orb almost supports publishing docker image to the Artifact repository but there are a couple of changes that need to happen for this to work.

## Examples:

```
executors:
  custom-docker-executor:
    machine:
      image: ubuntu-2004:202010-01    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      docker_layer_caching: true

# many lines in between
- gcp-gcr/build-and-push-image:
          executor: custom-docker-executor
          pre-steps:
            - checkout
            - run: ls -al
          context: ganus-example-stack-v2
          path: ./dataflow/
          workspace-root: ./dataflow/
          docker-context: ./dataflow/
          image: ganus-example-stack-v2/ganus-example-stack-v2-image
```

There two problems that make this fail:

1. the gcloud in the default executor is almost 200 version behind current version and thus does not allow specifying specific repositories when establishing docker credentials.  That problem was solved by using the later ubuntu machine defined as custom-docker-executor
2. the establishing docker credentials command has to have the registry passed-in for docker to recognize that push is authenticated

https://github.com/CircleCI-Public/gcp-gcr-orb/blob/b42aa3ccc0196538b50c3cf081abda9a37924fc8/src/commands/gcr-auth.yml#L46

needs to be changed to something like this:

```
gcloud auth configure-docker  $<<parameters.regisrty-url>> --quiet --project $<<parameters.google-project-id>>
```

## Supporting Documentation Links:

https://cloud.google.com/artifact-registry/docs/docker/authentication#gcloud-helper
