### ISSUE TITLE
`extra_build_args` parameter causes docker build error

### ISSUE THREAD

**Issue by imanmzoe** [CircleCI-Public/gcp-gcr-orb#48]
## Orb version:

0.13.0

## What happened:

when suppling `extra_build_args` it causes a docker build error: "docker build" requires exactly 1 argument."

## Expected behavior:

It should build the docker image successfully

## Additional Information:

circleci `config.yaml` file:

```yaml
# Define steps for individual jobs defined above
jobs:
  dbt_gcr_image:
    executor: python
    parameters:
      environment:
        description: Deployment environment
        type: string
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - setup_remote_docker:
          docker_layer_caching: true
      - gcp-gcr/build-image:
          image: dbt-bq-elt
          registry-url: eu.gcr.io
          extra_build_args: "--build-arg GCLOUD_SERVICE_KEY=$GCLOUD_SERVICE_KEY --build-arg GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID \
            --build-arg GOOGLE_COMPUTE_ZONE=$GOOGLE_COMPUTE_ZONE \
            --build-arg CIRCLE_BRANCH=$CIRCLE_BRANCH \
            --build-arg CIRCLE_USERNAME=$CIRCLE_USERNAME"
      - gcp-gcr/push-image:
          image: dbt-bq-elt
          registry-url: eu.gcr.io
```

generated docker build command: (i do not see anything wrong with it)

```
docker build --build-arg GCLOUD_SERVICE_KEY=$GCLOUD_SERVICE_KEY --build-arg GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID --build-arg GOOGLE_COMPUTE_ZONE=$GOOGLE_COMPUTE_ZONE --build-arg CIRCLE_BRANCH=$CIRCLE_BRANCH --build-arg CIRCLE_USERNAME=$CIRCLE_USERNAME \
  -f ./Dockerfile \
  $docker_tag_args \
  .
```
