### ISSUE TITLE
Build and push multiple tags

### ISSUE THREAD

**Issue by dshinzie** [CircleCI-Public/gcp-gcr-orb#49]
## Describe Request:
I was wondering if it was possible to build or push multiple tags using this orb. Currently it only looks like 1 string can be passed in

## Examples:

```
- gcp-gcr/push-image:
          image: pluto-api
          registry-url: gcr.io
          tag: [$CIRCLE_SHA1, "latest", "v2.2.1"]
```
