### ISSUE TITLE
Option to use buildkit

### ISSUE THREAD

**Issue by vpol** [CircleCI-Public/gcp-gcr-orb#62]
## Describe Request:
It would be nice to be able to pass option
`use-buildkit: true`
 to docker/build step

**Comment by danopia** [comment]
I found a workaround of enabling buildkit for the executor that I give to the gcp-gcr orb:

```yaml
executors:
  build:
    docker:
    - image: cimg/base:2022.04
      # Enable BuildKit for docker jobs:
      environment:
        DOCKER_BUILDKIT: '1'
```

It seems like the build log is very verbose with BuildKit, so maybe that can also be addressed somehow.
