### ISSUE TITLE
Unable to use interpolated var for pipeline values for "image:" in build-and-push-image job

### ISSUE THREAD

**Issue by m0ab** [CircleCI-Public/gcp-gcr-orb#66]
## Orb version:

0.15

## What happened:

```
version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.15

workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: ${CIRCLE_PROJECT_REPONAME}
          registry-url: us.gcr.io
          tag: ${CIRCLE_SHA1:0:7},latest
```

image: ${CIRCLE_PROJECT_REPONAME} should read as the pipeline value CIRCLE_PROJECT_REPONAME. It cannot be interpolated and returns error in pipeline "invalid reference format: repository name must be lowercase"

## Expected behavior:

Error should not exist. Variable should be interpolated. Image repository should be created using the value for CIRCLE_PROJECT_REPONAME.

## Additional Information:

Update gcp-gcr-ord/src/scripts/push-image.sh
Add `ORB_VAL_IMAGE=$(eval echo "$ORB_VAL_IMAGE")` on line 5 of push-image.sh

Tested and confirms that adding this works, the var is read properly, and the pipeline passes without failure

**Comment by YahiaElTai** [comment]
I'm facing the exact same issue after updating the orb to the latest version `0.15.1`
This is my usage

```yaml
      - gcp-gcr/build-and-push-image:
          name: build_and_publish_cart_image
          docker-context: ./services/cart
          image: $REPO_NAME/cart
          path: ./services/cart
          registry-url: $REGISTRY_URL
          tag: << pipeline.git.revision >>
          requires:
            - typecheck_and_test_cart
```

I will rollback to the previous version for now until this bug is fixed 🚀
