### ISSUE TITLE
gcr-auth error on Windows machine executor

### ISSUE THREAD

**Issue by bchu-oanda** [CircleCI-Public/gcp-gcr-orb#88]
## Orb version:

gcp-gcr: circleci/gcp-gcr@0.16.3
windows: circleci/windows@5.0.0

## What happened:

We are using a Windows machine executor to perform perform Docker builds and pushes. We use the gcp-gcr/gcr-auth command to authenticate to use our private container registry in GCP. The `gcloud auth configure-docker` step fails:
```
Adding credentials for all GCR repositories.
WARNING: A long list of credential helpers may cause delays running 'docker build'. We recommend passing the registry name to configure only the registry you are using.
Docker configuration file updated.
bash: line 17: sudo: command not found

Exited with code exit status 127
```

## Expected behavior:

The gcr-auth command succeeds on Windows executors.

## Additional Information:

CircleCI config.yml:
```
version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.3
  windows: circleci/windows@5.0.0

jobs:
  windows_build:
    executor:
      name: windows/server-2019
      shell: bash.exe -eo pipefail
    parameters:
      gcloud_version:
        type: string
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          use_oidc: true
      - gcp-gcr/build-image:
          dockerfile: Dockerfile.windows
          image: my-windows-test
          tag: << parameters.gcloud_version >>
      - gcp-gcr/push-image:
          image: my-windows-test
          tag: << parameters.gcloud_version >>

workflows:
  version: 2

  build:
    jobs:
      - windows_build:
          name: "<< matrix.gcloud_version >> Windows build"
          matrix:
            parameters:
              gcloud_version: ["471.0.0", "477.0.0"]
          context:
            - gar-rw
```
