### ISSUE TITLE
Job failing because default remote docker version will be deprecated

### ISSUE THREAD

**Issue by Rapol** [CircleCI-Public/gcp-gcr-orb#90]
## Orb version:

```
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.3

executors:
  gcp-executor:
    docker:
      - image: cimg/base:2024.05
...
workflows:
  merge-workflow:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: data
          executor: gcp-executor
          image:  ...
          registry-url: ...
          setup-remote-docker: true
          use-docker-layer-caching: true          
```

## What happened:

CircleCI failing because of 

> This job was rejected because the image 'Remote Docker version: docker-17.09.0-ce' is [unavailable](https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/)

Fix was to set:

remote-docker-version: docker24

## Expected behavior:

Orb should default to an approved remote docker version instead of defaulting to 17.09.0-ce which is being deprecated and part of circleci brownout.

## Additional Information:

Changing a default is usually pretty risky (will break people stuff) so Im thinking that changing the default value should be a mayor or minor release. Thoughts?
